platform_status_db/job_logs/urls.py
from django.urls import path

from . import views

app_name = 'job_logs'
urlpatterns = [
    path('', views.main_index, name='index'),
    path('devices/', views.IndexView.as_view(), name='devices'),
    path('movement_finder/', views.movement_finder, name='movement_finder'),
    path('present_labware/', views.LabwareView.as_view(), name='present_labware'),
    path('devices/<int:pk>/', views.DeviceView.as_view(), name='device_detail'),
    path('positions/<int:pk>/', views.PositionView.as_view(), name='position_detail'),
    path('containers/<int:pk>/', views.ContainerView.as_view(), name='container_detail'),
    path('jobs/<int:pk>/', views.JobView.as_view(), name='job_detail'),
    path('move_jobs/<int:pk>/', views.MoveJobView.as_view(), name='move_job_detail'),
]

platform_status_db/larastatus/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path('job_logs/', include('job_logs.urls')),
]

platform_status_db/job_logs/models.py
from __future__ import annotations
from django.db import models
from datetime import datetime, timedelta


class Device(models.Model):
    # app_label = 'job_logs'
    num_slots = models.IntegerField(default=1)
    lara_name = models.CharField(max_length=50)
    lara_uri = models.URLField()

    def __str__(self):
        return self.lara_name


class Position(models.Model):
    device = models.ForeignKey(Device, on_delete=models.CASCADE)
    slot_number = models.IntegerField()
    deep_well_suited = models.BooleanField(default=False)

    def __str__(self):
        return f'{str(self.device)}[{self.slot_number}]'


class Container(models.Model):
    current_pos = models.ForeignKey(Position, on_delete=models.CASCADE)
    starting_pos = models.ForeignKey(Position, on_delete=models.CASCADE, related_name='starting_pos')
    barcode = models.CharField(max_length=50)
    lidded = models.BooleanField('currently lidded')
    # in case there is no lid or the container is currently lidded, the following field is nulled
    lid_pos = models.ForeignKey(Position, on_delete=models.CASCADE, blank=True, null=True, default=None,
                                related_name='lid_pos')
    removed = models.BooleanField('got removed from platform', default=False)
    labware_uuid = models.UUIDField()

    def __str__(self):
        return f"Container({self.barcode})"


class Process(models.Model):
    name = models.CharField(max_length=200)
    pythonlab_description = models.TextField()
    process_uuid = models.UUIDField()


class Experiment(models.Model):
    experiment_uuid = models.UUIDField()
    process = models.ForeignKey(Process, on_delete=models.CASCADE)


class ProcessStep(models.Model):
    start = models.DateTimeField('job started')
    finish = models.DateTimeField('job finished')
    executing_device = models.ForeignKey(Device, on_delete=models.CASCADE)
    container = models.ForeignKey(Container, on_delete=models.CASCADE, blank=True, null=True, default=None)
    experiment = models.ForeignKey(Experiment, null=True, on_delete=models.CASCADE)
    process_name = models.CharField(max_length=200)
    is_simulation = models.BooleanField(default=True)
    # this will contain a json-string representing the kwargs with their args converted to str
    parameters = models.TextField(default='{}')

    def get_duration(self) -> float:
        # magically get converted to datetime
        return (self.finish - self.start).total_seconds()

    def __str__(self):
        return f"Step_{self.executing_device}_(process={self.process_name})"


class MoveStep(ProcessStep):
    origin = models.ForeignKey(Position, on_delete=models.CASCADE, related_name='origin')
    destination = models.ForeignKey(Position, on_delete=models.CASCADE, related_name='destination')
    lidded_before = models.BooleanField()
    lidded_after = models.BooleanField()
    barcode_read = models.BooleanField('read barcode on the way')
    uri_format = models.CharField(max_length=400)

    def __str__(self):
        return f"{str(self.origin)}-->{str(self.destination)}"


class Result(models.Model):
    step = models.ForeignKey(ProcessStep, on_delete=models.CASCADE)
    content = models.TextField()


class Decision(models.Model):
    pass


class Computation(models.Model):
    pass

platform_status_db/job_logs/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Device, Container, Position, ProcessStep, MoveStep


def main_index(request):
    context = {'sub_indices': ['devices']}
    response = render(request, 'index.html', context)
    return response


def movement_finder(request):
    response = render(request, 'movement_finder.html')
    return response


class IndexView(generic.ListView):
    template_name = "deviceindex.html"
    context_object_name = 'list'

    def get_queryset(self):
        return Device.objects.all()


class DeviceView(generic.DetailView):
    model = Device
    template_name = 'device_detail.html'
    context_object_name = 'device'


class LabwareView(generic.ListView):
    template_name = 'labware_detail.html'
    context_object_name = 'list'

    def get_queryset(self):
        return Device.objects.all()
        #return Container.objects.filter(removed=False)


class PositionView(generic.DetailView):
    model = Position
    template_name = 'position_detail.html'
    context_object_name = 'position'


class ContainerView(generic.DetailView):
    model = Container
    template_name = 'container_detail.html'
    context_object_name = 'container'


class JobView(generic.DetailView):
    model = ProcessStep
    template_name = 'job_detail.html'
    context_object_name = 'job'


class MoveJobView(generic.DetailView):
    model = MoveStep
    template_name = 'move_job_detail.html'
    context_object_name = 'move_job'

platform_status_db/job_logs/templates/container_detail.html
<h1>{{container}}</h1>
<li>Started at <a href="{% url 'job_logs:position_detail' container.starting_pos.id %}">{{container.starting_pos}}</a></li>
<li>Currently at <a href="{% url 'job_logs:position_detail' container.current_pos.id %}">{{container.current_pos}}</a></li>
<li>Lidded: {{container.lidded}}</li>
<li>Lid position: {{container.lid_pos}}</li>
<li>Removed from platform: {{container.removed}}</li>

platform_status_db/job_logs/templates/device_detail.html
<h1>{{ device }}</h1>

<ul>
{% for pos in device.position_set.all %}
    <li><a href="{% url 'job_logs:position_detail' pos.id %}">{{ pos }}</a></li>
{% endfor %}
</ul>

platform_status_db/job_logs/templates/deviceindex.html
{% if list %}
    <ul>
    {% for elem in list %}
        <li><a href="{% url 'job_logs:device_detail' elem.id %}">{{ elem }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No Device in database.</p>
{% endif %}

platform_status_db/job_logs/templates/index.html
<li><a href="{% url 'job_logs:devices' %}">Device List</a></li>
<li><a href="{% url 'job_logs:movement_finder' %}">Movement Finder</a></li>
<li><a href="{% url 'job_logs:present_labware' %}">Present Labware</a></li>

platform_status_db/job_logs/templates/job_detail.html
{{job}}

platform_status_db/job_logs/templates/labware_detail.html
{% if list %}
    <ul>
    {% for elem in list %}
        <a href="{% url 'job_logs:device_detail' elem.id %}">============ {{ elem }} ==============</a>
        <br>
        {% for pos in elem.position_set.all%}
            {% for cont in pos.container_set.all%}
                {% if not cont.removed %}
                    <li><a href="{% url 'job_logs:container_detail' cont.id %}">{{ cont }}</a> at {{pos}}</li>
                {% endif %}
            {% endfor %}
            {% for cont in pos.lid_pos.all%}
                {% if not cont.removed %}
                    <li>Lid of <a href="{% url 'job_logs:container_detail' cont.id %}">{{ cont }}</a> at {{pos}}</li>
                {% endif %}
            {% endfor %}
        {% endfor %}
        <br>
    {% endfor %}
    </ul>
{% else %}
    <p>No labware in database.</p>
{% endif %}

platform_status_db/job_logs/templates/move_job_detail.html
{{move_job}}

platform_status_db/job_logs/templates/movement_finder.html
<h1>Movement Finder</h1>

platform_status_db/job_logs/templates/position_detail.html
<h1>{{ position }}</h1>
<li><a href="{% url 'job_logs:device_detail' position.device.id %}">{{ position.device }}</a></li>
<p>present containers:</p>
{% if position.container_set.all %}
    <ul>
    {% for container in position.container_set.all %}
        <li><a href="{% url 'job_logs:container_detail' container.id %}">{{container}}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Position is empty.</p>
{% endif %}